[package]
name = "rust-music-player"
version = "0.1.0"
authors = ["Matthias Kr√ºger <matthias.krueger@famsik.de>"]

[dependencies]
rodio = "0.5.2"
ncurses = "5.86.0"
clippy = "*"
walkdir = "1.0.7"

[features]
default = []

[profile.release]
opt-level = 3
lto = true
